### ISSUE TITLE
missing macro

### ISSUE THREAD

**Issue by sirkerry** [omonubi/ACKS-by-omonubi#5]
it appears that the skills.txt macro is missing from the repository

**Comment by omonubi** [comment]
Apologies. I sometimes forget to update the macros list and files for this repo. The issue is that something that looks like its a good idea turns out not to be very useful and then I nix it from my game. In this case, I stopped using a Skills macro as described in the readme. I no longer have a copy of the script.

**Comment by omonubi** [comment]
See above
